before_install:
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update


install:
  - sudo apt-get install -qq libboost1.55-all-dev gcc-4.8 g++-4.8 clang-3.4 ninja-build

language: cpp

compiler: clang

before_script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..

script:
  - ninja
