before_install:
  - sudo add-apt-repository --yes  ppa:boost-latest/ppa
  - sudo apt-get -q update
  - sudo apt-get install libboost-all-dev

language: cpp

compiler: clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make